# Generated by Django 5.0.4 on 2024-05-02 08:34

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Patients',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Patient_ID', models.IntegerField(max_length=200)),
                ('Name', models.CharField(max_length=200)),
                ('Age', models.IntegerField(max_length=200)),
                ('Disease', models.CharField(max_length=200)),
                ('Location', models.CharField(max_length=200)),
            ],
        ),
    ]
